// AUTO-GENERATED by scripts/optimize-media.mjs — do not edit.
// Run `npm run media` after changing scripts/media.config.mjs.

export type Rendition = {
  readonly slug: string;
  readonly alt: string;
  readonly width: number;
  readonly height: number;
  readonly aspect: number;
  readonly lqip: string;
};

export const IMAGE_WIDTHS = [640,1080,1600,2400] as const;

export const IMAGES = {
  "facade-dusk": {
    "slug": "facade-dusk",
    "alt": "The facade at dusk, seen up through the rain trees",
    "width": 3848,
    "height": 1693,
    "aspect": 2.2729,
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAwCdASoUAAkAPwl0sFCrpySisAgBcCEJaQAASqu/ztn4ZMXOAAD+pRrSLw3h1ljxMSmBsB7dw58AAAA="
  },
  "facade-canopy": {
    "slug": "facade-canopy",
    "alt": "Rain trees arching over the building front on 46th Street",
    "width": 3848,
    "height": 1744,
    "aspect": 2.2064,
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUAAkAPwl0s1CrpySisAgBcCEJaQAALE80iSoM1kQA/R2frVLvdjwiz2mo7VkN9d2EPCY1AAA="
  },
  "facade-street": {
    "slug": "facade-street",
    "alt": "The building seen from the street corner, Ashok Nagar",
    "width": 3848,
    "height": 1795,
    "aspect": 2.1437,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAABQAwCdASoUAAkAPwl0sFCrpySisAgBcCEJaQAAK2mNqUx8EADf59l8MudPmtfAjz1XI3V4XurGPEId2gAAAA=="
  },
  "facade-side": {
    "slug": "facade-side",
    "alt": "Side elevation under the tree canopy",
    "width": 3848,
    "height": 1795,
    "aspect": 2.1437,
    "lqip": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABwAwCdASoUAAkAPwlwr1ArpqQisAgBcCEJaQAATt3Xu7hAaAAA/u7evzaSD7ayscIz/+fiDgkAAA=="
  },
  "sky-cutout": {
    "slug": "sky-cutout",
    "alt": "Monsoon cloud seen through the roof terrace cutout",
    "width": 3926,
    "height": 5889,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwBACdASoUAB4APvVeq0+qpKQiN/qoAVAeiWkAAO0mnPG9gDJlqqMuJtC/H90mPQAA/c6ilCXSVA43dsekRwyczbhZdU0G/YPcAAAA"
  },
  "parking-bay": {
    "slug": "parking-bay",
    "alt": "Covered parking bay beneath the building",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAABwAwCdASoUAA0APwlwsE+rpqSiMAgBcCEJaQAAKPDQAMITA5wA+bd502Xv9py99qQMyUCZk5J4/CnMeAAAAA=="
  },
  "lift-stone": {
    "slug": "lift-stone",
    "alt": "Brushed steel lift doors set into dark granite",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAwCdASoUAA0APwlyr0+rpyQiMAgBcCEJaQAAVETBNlfO1rEkyAAA/F2dA45j3BkENnAZtICePvkE4AgKQSAmHcAAAA=="
  },
  "lift-wide": {
    "slug": "lift-wide",
    "alt": "The lift lobby with a doorway opening onto daylight",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoUAA0APwlys1CrpqSisAgBcCEJaQAAWRoRYdYkU9AuwAD9dxnZ3u9j/GOz39xYf+dGsb1685rogS6cHdXOGLkMAAA="
  },
  "stair-flight": {
    "slug": "stair-flight",
    "alt": "The stair flight turning against a white wall",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAA0APwlurk+rpiQiMAgBcCEJaQAAW9YYGV1l0P2vAAD5Wiv+k2UxS/47KFGOwmjTu03H5tA+AAAA"
  },
  "stair-palm": {
    "slug": "stair-palm",
    "alt": "A palm at the foot of the stairs beside an open room door",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAwCdASoUAA0APwlysFArpySisAgBcCEJaQAARP2ZssKAc07OSggA/pfc2/z7hnzJrKnxJd0O+a+vPn8K/Iglq4AAAA=="
  },
  "corridor-door": {
    "slug": "corridor-door",
    "alt": "Guest room doorway along the corridor",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAwCdASoUAA0APwl0sFCrpySisAgBcCEJaQAAPSSZuuwnwqegAP3636NsmIH6XNy10bSK8R46ZeiyCykg7W+6neoAAA=="
  },
  "room-a-bed": {
    "slug": "room-a-bed",
    "alt": "King bed centred beneath the headboard wall in a Studio King",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAwCdASoUAA0APwlusE+rpiSiMAgBcCEJaQAAQvbSvVUvuEXyDkAA/rGAYOBkm1qGPEWCU19zaC6GOaydbhkdtjpVYpUAAAA="
  },
  "room-a-wide": {
    "slug": "room-a-wide",
    "alt": "Studio King seen toward the door, desk and chair at the window",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAwCdASoUAA0APwlurk+rpiQiMAgBcCEJaQAAMH1pE9WG2AAA9b65iB/8QiLbS1e+FIiVYOzW5Sdnm2QTHRfAAAA="
  },
  "room-a-window": {
    "slug": "room-a-window",
    "alt": "Morning light through the window of a Studio King",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoUAA0APwlurk+rpiQiMAgBcCEJaQAAUzLwerDSF2sIAP3PHmtfSDwjpMDHLY/mHtsNX9RsOAA="
  },
  "room-a-bath": {
    "slug": "room-a-bath",
    "alt": "Bathroom with tiled dado and walk-in shower",
    "width": 9378,
    "height": 7008,
    "aspect": 1.3382,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoUAA8APwlysFArpySisAgBcCEJaQAAUTBP/p1h/EqwAAD+1dx81UcwwPlThvWnmGIlnquK7JMBqiQAAAA="
  },
  "room-b-bed": {
    "slug": "room-b-bed",
    "alt": "Bed and headboard in a Corner Twin",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABQAwCdASoUAA0APwlurk+rpiQiMAgBcCEJaQAATy2i+FUgAADh3d955z0s2ZKECMYGMZnn5fp0DHcWWPzphAAA"
  },
  "room-b-wide": {
    "slug": "room-b-wide",
    "alt": "Corner Twin seen from the entry",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoUAA0APwlyr0+rpyQiMAgBcCEJaQAAO2jx21itjAAA/JjaQJ7puslYBM9/SPqAIY8y6QeKOkdUJ1O+bIM9s+iRuAAAAA=="
  },
  "room-b-light": {
    "slug": "room-b-light",
    "alt": "Daylight across the floor of a Corner Twin",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQAwCdASoUAA0APwlysVArpqSisAgBcCEJaQAAT5clWtnzQAD86PWJR3IQg9ITV4UcHuJdOy66JGRHYmD+IwKnnTFNAAAA"
  },
  "room-twin": {
    "slug": "room-twin",
    "alt": "Two single beds made up under the artwork wall",
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBQCdASoUAB4APwlyrk+rpyQiMBgMAXAhCWkAACG8cz0q/9lSKnzwtAZye8rohPQCAAD+3G+NTLnHZdxh3rZPhy24r6orMEYaX7V+oPAruSPRovfrbO19epV51nQAAAA="
  },
  "room-pillows": {
    "slug": "room-pillows",
    "alt": "Pillows and turned linen against the timber headboard",
    "width": 3989,
    "height": 5983,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwBACdASoUAB4APwlwrU+rpqQiMAgBcCEJaQAAQckMC1MVHPreKxjf+8SAeHoF+oAA/u9betlmJa4gmsZem1g1HI0Hf83LppOtiiVms+L2c1HgWfVW/SOYAIv0Jt+5BMbuVnaQw0AAAA=="
  },
  "room-headboard": {
    "slug": "room-headboard",
    "alt": "Concealed light washing the headboard",
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQBACdASoUAB4APv1qrU+rJiSiMAwBYB+JaQAASn4UjZr1q2fXkuDCoVUzID3qAAD8ofOJIQ7I3zyUVbyX9DEJe0KRKkFXPZfg+q57foZfZpAdUBelNmqFMSnKXNlpsVKJ2QAA"
  },
  "room-lounge": {
    "slug": "room-lounge",
    "alt": "Leather seating and a low table in the lounge suite",
    "width": 3932,
    "height": 5898,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQBACdASoUAB4APwl6sFCrqKSisBgIAXAhCWkAAI7Jl4+wJ7LtQJ9fwxhULw+EAAD+5+tKYEndG5TVIaRnPaNdLoJwz1j3joq0LVsqXfuBNjVBYoJU5pGGY7ZcDM3XdgGzdfpu/i4eRhGAAAA="
  },
  "detail-number": {
    "slug": "detail-number",
    "alt": "Room 306 in brass numerals on a dark door",
    "width": 3996,
    "height": 5994,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwBACdASoUAB4APwl0tlMrpqUisBgIAXAhCWkAAI91m3Q1AA8d3S8RGtezx0AgAP30CJihgpRQm1eQyAHJKdl/k+NIMmM/Ny6kO3w+nCAAAA=="
  },
  "detail-switch": {
    "slug": "detail-switch",
    "alt": "The do-not-disturb switch plate beside the bed",
    "width": 3979,
    "height": 5969,
    "aspect": 0.6666,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwBACdASoUAB4APwl6sVOrp6QiqAqpcCEJaQAAHPqT48HC7MGvo23olN2ldi1gAP7nJXoW7hiFOELVKjIL5qWV5qQe4FBWsx24wy+s0Znm5Ihg8D/lJc9zy2Y9kukUt5tGSZTntxiAAA=="
  },
  "detail-latch": {
    "slug": "detail-latch",
    "alt": "Brass door chain resting against the frame",
    "width": 3867,
    "height": 5800,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwBACdASoUAB4APwlwsU+rpqSiMAgBcCEJaQAAUz7KP+6MOJY3OmTk2sj5CAD+xr/Jr5TSQ7Lwq1Y0vLXQ7Q6M2RTM/edujZQr1pdRgNL3GDoOQgYqHH8i3LGMx0QgAAA="
  },
  "detail-lock": {
    "slug": "detail-lock",
    "alt": "Keycard lock set into the timber door",
    "width": 3940,
    "height": 5910,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwBACdASoUAB4APwl0s1IrpqSisBgIAXAhCWkAAC5Gcep+CQ9Jh6lEwJES3GeAAP65r0A5NM+bUlkeau4NfwhjJFB2OTlYPULLQydSB0AAAA=="
  },
  "detail-books": {
    "slug": "detail-books",
    "alt": "Two paperbacks left on the bedside table",
    "width": 3984,
    "height": 5976,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwBACdASoUAB4APwlus1KrpaSisBgIAXAhCWkAAI94GvQ7Mg5htsfkuAiRdDwAAP7u2WJevT5YfTvBm4rcJhjsUz1O8UgXvxTrQi2jVTIil/QOQCC3ZpJazyjHwDBOOuYAAA=="
  },
  "detail-curtain": {
    "slug": "detail-curtain",
    "alt": "Curtains parted on the afternoon",
    "width": 3945,
    "height": 5918,
    "aspect": 0.6666,
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQBACdASoUAB4APwlyr0+rpyQiMAgBcCEJaQAAO0DKlLOjk6VOHUtK/1mlpPv1AAD+r5qNdkN6TMjEs6LUh7zasG7aoQrlGOg/FEmD/os9kIcnj6KByWfTbC0yTBEafLOxT5k/zVQk2AAA"
  },
  "reception-desk": {
    "slug": "reception-desk",
    "alt": "Pendant lights over the split stone wall at reception",
    "width": 2309,
    "height": 1590,
    "aspect": 1.4522,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoUAA4ALs2EwmEjq6uri4DMS0gABENKR0tJiK6cWlUAAP33fGly6gQOq2DUKtNAbLpHj24P5ufBogAA"
  },
  "reception-wide": {
    "slug": "reception-wide",
    "alt": "The fluted glass door onto the arrival hall",
    "width": 1770,
    "height": 2565,
    "aspect": 0.6901,
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwBACdASoUAB0APwl0s1IrpqSisBgIAXAhCWkAACBarm0LeupiJqhr+V8izyQyyGQA/uno46kyUEofejZloUiOkfVT6nZ/gXx6NYE4+b+w3pMe1VJ8nt1gNWUAAA=="
  },
  "dining-room": {
    "slug": "dining-room",
    "alt": "The dining room laid for breakfast service",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAwCdASoUAA0APwlusE+rpiSiMAgBcCEJaQAAW+hM6Hr0TNNkHZAAAP7DmEICnSLoISzNeA7QBuQ3VtrakWixIazgAAAA"
  },
  "dining-wide": {
    "slug": "dining-wide",
    "alt": "Dining room looking toward the windows",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAA0APwlys1CrpqSisAgBcCEJaQAAW7Or41SQO6/5mAD+w5fs5K0SVS6XKj9XnkWhNjIDZbJbgqbwNpBoAAAA"
  },
  "dining-counter": {
    "slug": "dining-counter",
    "alt": "The breakfast counter and service line",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAwCdASoUAA0APwlurk+rpiQiMAgBcCEJaQAAW+uCshd6E9GAAP7UHF6ZH1yBZYwmxte/GX0Q1Qu9PU0P5+i+f0AAAA=="
  },
  "conference-room": {
    "slug": "conference-room",
    "alt": "The conference room set for a working session",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAwCdASoUAA0APwlur0+rpiQiMAgBcCEJaQAAWlmQ9BhclAAA/q9JEmuZrXsn8O5wRZO+XjH4cwyyMQNoTpQAAAA="
  },
  "conference-wide": {
    "slug": "conference-wide",
    "alt": "Conference room with projection wall",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAwCdASoUAA0APwlwr0+rpqQiMAgBcCEJaQAAQ9VJpNaTCICAAP6MZjCZvOvV6OBnLY0JE2aJawSz32zjS0YAAAA="
  },
  "common-area": {
    "slug": "common-area",
    "alt": "The common lounge on the upper floor",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAwCdASoUAA0APwlurk+rpiQiMAgBcCEJaQAAUq1CTvmla0y2uAD+05anDyIo3YtmQAqewuCiQP8wPASQAA=="
  },
  "common-wide": {
    "slug": "common-wide",
    "alt": "Long view across the common area",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAwCdASoUAA0APwlys1CrpqSisAgBcCEJaQAAUkhQNgXE4e+AAN2g9wFl7GV3vsBDY5C7SAy9AItBWsAAAA=="
  },
  "breakfast-plate": {
    "slug": "breakfast-plate",
    "alt": "South Indian breakfast plated with sambar and chutney",
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACQBQCdASoUAB4APwlws1KrpaSisBgIAXAhCWkAAI6OA457jIM4QqjmtxEFQrkXaKjx3w2YAAD+cD1SmqyC3FzRyY0WNNg9xuJyIZnVk+XyceXmkuxHPzjgQ1Z19wTBMcHwySVQ4wLhge9f50p08DF4gAA="
  }
} as const satisfies Record<string, Rendition>;

export const VIDEOS = {
  "reel-morning": {
    "slug": "reel-morning",
    "alt": "Curtains drawn open onto the morning",
    "width": 608,
    "height": 1080,
    "aspect": 0.563,
    "lqip": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAgCdASoQABwAA8BmJaQAApxQh3Mg9vFkQAD+ZAuaXairOSs1oTrc/e9Afyr/4BsTjLU5tgAAAA=="
  },
  "reel-tea": {
    "slug": "reel-tea",
    "alt": "Tea made in the room",
    "width": 608,
    "height": 1080,
    "aspect": 0.563,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoQABwAPwl0s1CrpySisAgBcCEJaQAANy1+fLJP8xa4tfoAAK6DBbyHz3/+N6EVSqGmNXztzG48ee656gVL1Y4P3V5o8s5Iv8VpWcy8AoYTz0EAAAA="
  },
  "reel-common": {
    "slug": "reel-common",
    "alt": "Guests around the table in the common area",
    "width": 608,
    "height": 1080,
    "aspect": 0.563,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoQABwAPwlMvVmroqekmAFwIQlpAABLMtkOTD5gjS1oAAD9QlycsuFq90D+JEiWLzRQVBvqgGz845CI+uRsc/BTJUlyrsQAAAA="
  }
} as const satisfies Record<string, Rendition>;

export type ImageSlug = keyof typeof IMAGES;
export type VideoSlug = keyof typeof VIDEOS;
