// AUTO-GENERATED by scripts/optimize-media.mjs — do not edit.
// Run `npm run media` after changing scripts/media.config.mjs.

export type Rendition = {
  readonly slug: string;
  readonly alt: string;
  readonly width: number;
  readonly height: number;
  readonly aspect: number;
  readonly lqip: string;
};

export const IMAGE_WIDTHS = [640,1080,1600,2400] as const;

export const IMAGES = {
  "facade-dusk": {
    "slug": "facade-dusk",
    "alt": "The facade at dusk, seen up through the rain trees",
    "width": 3848,
    "height": 1693,
    "aspect": 2.2729,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoUAAkAPwlurk+rpiQiMAgBcCEJYwAAWo7YSUPricAAAP57sTvFTskGOERqtwxp1aXPnEpAUNa5AAAA"
  },
  "facade-canopy": {
    "slug": "facade-canopy",
    "alt": "Rain trees arching over the building front on 46th Street",
    "width": 3848,
    "height": 1744,
    "aspect": 2.2064,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAwCdASoUAAkAPwlyr1ArpyQisAgBcCEJZgCsABTuPQYLNXY+48AA+dmYwCGH2Qw3eLje1VHRp04p1RsQwmbprYgD2AAA"
  },
  "facade-street": {
    "slug": "facade-street",
    "alt": "The building seen from the street corner, Ashok Nagar",
    "width": 3848,
    "height": 1795,
    "aspect": 2.1437,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoUAAkAPwlur0+rpiQiMAgBcCEJYgC7ABE7H784c6qAAADf59lOGBIfVYk5YrnOw1O+Yhr6CiyncCpGNwAAAA=="
  },
  "facade-side": {
    "slug": "facade-side",
    "alt": "Side elevation under the tree canopy",
    "width": 3848,
    "height": 1795,
    "aspect": 2.1437,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAwCdASoUAAkAPwlwr1ArpqQisAgBcCEJZQC/OB06ScR9ISCkAAD+5CK2AYZJGYBXVorx/PMIpUVw6vbgAA=="
  },
  "sky-cutout": {
    "slug": "sky-cutout",
    "alt": "Monsoon cloud seen through the roof terrace cutout",
    "width": 3926,
    "height": 5889,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwBACdASoUAB4APuliqE+zJaQiN+gCYB0JZQC2yDJSwRxN+7y96T/Gc/tFhQKAAPxRxpv46ar6NcG1314uCrpc1kusTBiUWTtENPkDPI/mAA=="
  },
  "parking-bay": {
    "slug": "parking-bay",
    "alt": "Covered parking bay beneath the building",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAwCdASoUAA0APwlwsFArpiSisAgBcCEJZQCdMoAC6m7ks+krYACfQoV6O1fabKos2uJ7Hxp5ALG+3oReAAAA"
  },
  "lift-stone": {
    "slug": "lift-stone",
    "alt": "Brushed steel lift doors set into dark granite",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoUAA0APwlwrk+rpqQiMAgBcCEJZACdMoAC6n+njl0Sv6egAPxcSQkg8hzx5zwQ5O4XnjWjhGRtsDgqgS7SQx6tdJkDolGg0cYh6R7AAAA="
  },
  "lift-wide": {
    "slug": "lift-wide",
    "alt": "The lift lobby with a doorway opening onto daylight",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoUAA0APwlwsFArpiSisAgBcCEJQBOmUI4AAtPdTqw8UnfAAPQxT3CpMnz0VPzsIZhoOx6MBQyYlhapN/afweXKRFfYGh4DHUr2gAAA"
  },
  "stair-flight": {
    "slug": "stair-flight",
    "alt": "The stair flight turning against a white wall",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoUAA0APwlurk+rpiQiMAgBcCEJQBOmUABpuiD43fDQAAD5KK3R+c6d9War7PAmLh+E8yBCd21nGv4rNLSZRAmwGnJsgAAA"
  },
  "stair-palm": {
    "slug": "stair-palm",
    "alt": "A palm at the foot of the stairs beside an open room door",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoUAA0APwlwr1ArpiQisAgBcCEJQBdgApXaXSPl9zQaVQAA/mYAFVyF+qZOYUVDRL1pitMtWzyDEM8bVIHq7ln8AAAAAA=="
  },
  "corridor-door": {
    "slug": "corridor-door",
    "alt": "Guest room doorway along the corridor",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoUAA0APwlwr1ArpiQisAgBcCEJQBUegzMsThFLhHk9AAD80rs5UdMrZNSwMkP4K14Q8UgvH94qbg5cVnoooBx+AAA="
  },
  "room-a-bed": {
    "slug": "room-a-bed",
    "alt": "King bed centred beneath the headboard wall in a Studio King",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoUAA0APwlwr0+rpqQiMAgBcCEJYwCsABjWCYbxSli8AP6QeqcGbiSN+8kucJD3SsKM6O0QK5RLRNNHSHkQ0fRkHwT+aKcqwAA="
  },
  "room-a-wide": {
    "slug": "room-a-wide",
    "alt": "Studio King seen toward the door, desk and chair at the window",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoUAA0APwlyr1ArpyQisAgBcCEJQBOmUI+PA7j7DSb7pyQAzRH5LDuynkaldwxFRBwg90DLnClKezwFyjxLZC7kwYkAAA=="
  },
  "room-a-window": {
    "slug": "room-a-window",
    "alt": "Morning light through the window of a Studio King",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAwCdASoUAA0APwlwr0+rpqQiMAgBcCEJYwCdMoABp0ZyjglQHYAA/c6yqwDFb2Q9AgbyR6d6eRT9cALIIimtCULBJ0AA"
  },
  "room-a-bath": {
    "slug": "room-a-bath",
    "alt": "Bathroom with tiled dado and walk-in shower",
    "width": 9378,
    "height": 7008,
    "aspect": 1.3382,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAwCdASoUAA8APwlyr1ArpyQisAgBcCEJZQCdAB4I5fWgPL2oUYnAAP7HFlLLJaMR2gVHdencTGvlAAURaxIAAAA="
  },
  "room-b-bed": {
    "slug": "room-b-bed",
    "alt": "Bed and headboard in a Corner Twin",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAA0APwlur0+rpiQiMAgBcCEJYwCdABK5aA35T1kCAADhcgPm9FWRhvJKOKJVFTXfRN9AKImW+82WwMB0wAAA"
  },
  "room-b-wide": {
    "slug": "room-b-wide",
    "alt": "Corner Twin seen from the entry",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABwAwCdASoUAA0APwlwr0+rpqQiMAgBcCEJYwCdAAMWQIjNQgAA/E6wSDmIUewLW6bI2geJnZ/QZBnpjKaDw+MUFhVcze0TpNYcdAAA"
  },
  "room-b-light": {
    "slug": "room-b-light",
    "alt": "Daylight across the floor of a Corner Twin",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAwCdASoUAA0APwlwsFArpqSisAgBcCEJZQCdMoABi6LLQMAA/Oj0od9nNtsQJz8IqEZIxObB5yr7SAVS8eLciYbK6M3QAAA="
  },
  "room-twin": {
    "slug": "room-twin",
    "alt": "Two single beds made up under the artwork wall",
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwBACdASoUAB4APwlssVIrpSSisBgIAXAhCWMAsOwN0F5ebv5Jgr6eZ4kbmVlTmkAA/qha72pZHdfqRzG5PzQMB2NKJ4PkiyCXEzAilBIZ5vWllOO6yUkYEqwsZmtnjtHh8YSD7wAAAA=="
  },
  "room-pillows": {
    "slug": "room-pillows",
    "alt": "Pillows and turned linen against the timber headboard",
    "width": 3989,
    "height": 5983,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwBACdASoUAB4APwlysFGrpqSisBgIAXAhCUAToAX2ulnjkPj0Rwn6pK3anW0AAP7szH+dVUV6aE8HdwQFU0POZMHNIxQ1XKI0i3WvUe1X9pcUSbpKY8neoVv8xqslb/H8Q8/kFmGXRUJsL6FZ+AAA"
  },
  "room-headboard": {
    "slug": "room-headboard",
    "alt": "Concealed light washing the headboard",
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBQCdASoUAB4APv1qqk+rJiOiMAwBYB+JQBWGbIBV+9txe6MQSAVT6QziDWoN3Vj9wAD8XdlQnMxf/ns7Ow8pSahKG1on4ru1FAwBhBjFKKG7RcAfo6AsW9GkZfkHBMCJYg9DSh8svLjX18NkKKTaP0zPCAAA"
  },
  "room-lounge": {
    "slug": "room-lounge",
    "alt": "Leather seating and a low table in the lounge suite",
    "width": 3932,
    "height": 5898,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQBACdASoUAB4APwFuqE+rJqOiMAwBYCAJQBOgA2lN2dUHxYGZXh+6QfSD309cgAD+1duuhjjyhevrK3Wh6PkYwmO6iZ/OI6gjy7c5O3DxTQHpGCYa7s/QEiRwCL/6cAAsJjpWQWzUCNloMOidV+UWA8RLEIlrjAA="
  },
  "detail-number": {
    "slug": "detail-number",
    "alt": "Room 306 in brass numerals on a dark door",
    "width": 3996,
    "height": 5994,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBACdASoUAB4APv1srk+rJiSiMAwBYB+JaAC7M4CC/LmO0UswMLUQbJn+AAD8XIVxdUFLFKDX+vWUJqq/5HNEGLYcoCqRmuL2pDACkb2owGuAAmp0VaFIMTJjBv5GQUq0b8eltbIqrRw7SfphQAAA"
  },
  "detail-switch": {
    "slug": "detail-switch",
    "alt": "The do-not-disturb switch plate beside the bed",
    "width": 3979,
    "height": 5969,
    "aspect": 0.6666,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBACdASoUAB4APwl+t1UrqCUjKAgBcCEJQBWAAPBaGHMAaXpjfRz2RBfmAAD+02FZxwobCXJlQF2dY5e+TvBVyJyb3KSVCY7JrHyMavn4OveDFW1TdyQ6b+xaBmTevW9Zi5Y7fnnusj3EM72atuw4b9I43AAA"
  },
  "detail-latch": {
    "slug": "detail-latch",
    "alt": "Brass door chain resting against the frame",
    "width": 3867,
    "height": 5800,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwBACdASoUAB4APwlyr0+rpyQiMAgBcCEJYwC2yB4Y22PlI0XK8PdeKef2CtwAAP6vnzPkmppeVXR5bVyOHYVdD3CuHBeucHsjcQVBqBQh+BskJxJu3ztrrahx8EyBZ6V3UcefsAA="
  },
  "detail-lock": {
    "slug": "detail-lock",
    "alt": "Keycard lock set into the timber door",
    "width": 3940,
    "height": 5910,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAB4APwl8tVUrp6SjKAgBcCEJQAAFyB94evc/M5dCtjT4dAAA/p2GTPbIXRjiav/69UtcNf/O1bMA92MurzHLGYfN6plkAjjqSBUtmxZny8qtCJ8V6QAA"
  },
  "detail-books": {
    "slug": "detail-books",
    "alt": "Two paperbacks left on the bedside table",
    "width": 3984,
    "height": 5976,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwBACdASoUAB4APv1ork+rJiSiMAwBYB+JQBadBDwwJSGSefK/ZLCgiSVD0AD+y4oYZj8fqdcKrSNXt/PhAnWwUeogdseaCh3TK0/hSETyjDpkyOyoX+PXT9yBMskv+oZWwbxA5WDlQAAA"
  },
  "detail-curtain": {
    "slug": "detail-curtain",
    "alt": "Curtains parted on the afternoon",
    "width": 3945,
    "height": 5918,
    "aspect": 0.6666,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBQCdASoUAB4APwl0slIrpqSisBgIAXAhCWMAnQANrIGMfDLZjgYqmSg2wSyq6Y4gcAAA/o0rGdrBQjwSV/PtCbKxg35pBGGfrI1iZQqLQtqB0bfruDHVMzXfSaV1DUrlZlTE+5kvu8krzFKjA7t/R93Wp7CAAAA="
  },
  "reception-desk": {
    "slug": "reception-desk",
    "alt": "Pendant lights over the split stone wall at reception",
    "width": 2309,
    "height": 1590,
    "aspect": 1.4522,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAA4APwlws0+rpqUiMAgBcCEJZQAAUVh1O8dTTIFOUAD8xo8CPNcU4+96GmDdfaf7UZgUNR56WxouvTG1VUAA"
  },
  "reception-wide": {
    "slug": "reception-wide",
    "alt": "The fluted glass door onto the arrival hall",
    "width": 1770,
    "height": 2565,
    "aspect": 0.6901,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwBACdASoUAB0APwlsrlArpaQisBgMAXAhCWIAAIFUN8FOUwmmW5Gxs++RLuXwAP7diDAufItnvx4srnxgKb/MnjmRwDHq2tPMA96ZE0Ng5J1DwCA0Ik85OyN+oOMJ7e7NK7XVAAA="
  },
  "dining-room": {
    "slug": "dining-room",
    "alt": "The dining room laid for breakfast service",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQBACdASoUAA0APwlur0+rpiQiMAgBcCEJZACdMoRwACmn8/L4kaV7iHV4AP6u+kydQNOhxOzCbDWSdoPzCWNuM+2fTmx2PCEeQadcQr6PKJwA"
  },
  "dining-wide": {
    "slug": "dining-wide",
    "alt": "Dining room looking toward the windows",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoUAA0APwlurk+rpiQiMAgBcCEJZACdMoAC+az5ob3yWmkeYAD+r5b/hpSgstU3Hs51LvtFSwLgTeLPDNOV0a7O6PB/M1k7nSFtI664AAA="
  },
  "dining-counter": {
    "slug": "dining-counter",
    "alt": "The breakfast counter and service line",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAwCdASoUAA0APwlusFArpiSisAgBcCEJZACxC8ADApzT55EyZtYIAP7ErFg/+jtlvAgUta7Fw64W1yAUE1qDYwifa8HdhzVvXrWbQgOAAA=="
  },
  "conference-room": {
    "slug": "conference-room",
    "alt": "The conference room set for a working session",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoUAA0APwlur0+rpiQiMAgBcCEJQBYja5ApQn7voLvHNwAA/ozrhEspR0ebCRlcuFHz6oa7XrAHfvJ2rwkxTEeyvtUHAX9uVcFOAAAA"
  },
  "conference-wide": {
    "slug": "conference-wide",
    "alt": "Conference room with projection wall",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQBACdASoUAA0APwlwr1ArpqQisAgBcCEJYgCdMoACtA1LutZ1gjGgAAD+Uwxs7eSSQfDDgt/CpvRSo1uiP+Leqm/1jGmX8+TEAAAA"
  },
  "common-area": {
    "slug": "common-area",
    "alt": "The common lounge on the upper floor",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQBACdASoUAA0APwlwsFArpiSisAgBcCEJQBOmUABshchnZviFQbjpAAD+rqfg/lxlvVsTFpkdST8OaoVHLWMFREbgAA=="
  },
  "common-wide": {
    "slug": "common-wide",
    "alt": "Long view across the common area",
    "width": 3848,
    "height": 2565,
    "aspect": 1.5002,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoUAA0APwlys1CrpqSisAgBcCEJYgCdMoKCAAoRCyDoEPoAAPex3gsVQuZcuJ9pQzGME9D5KimpgbIXfJegZmZB/WqdRWnYyI2LgAAA"
  },
  "breakfast-plate": {
    "slug": "breakfast-plate",
    "alt": "South Indian breakfast plated with sambar and chutney",
    "width": 4000,
    "height": 6000,
    "aspect": 0.6667,
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwBACdASoUAB4APv1urE+rJqSiMAwBYB+JQBUeglXiTo3lTT4d6EdhFzwyXxiAAP0SYGpxoS+ogpL1PxIkNBzs/ezJlsA7XukrwjkFg59wrXGqpU69LVpoqSthAFPtp4FkV3ybsh9F4K1K4vsNygIN1UAAAA=="
  }
} as const satisfies Record<string, Rendition>;

export const VIDEOS = {
  "reel-morning": {
    "slug": "reel-morning",
    "alt": "Housekeeping making up a room in the morning",
    "width": 608,
    "height": 1080,
    "aspect": 0.563,
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoQABwAPwlur0+rpiQiMAgBcCEJZACdABEGllhVL+QHsAD+UmkWdst5bcHz8vJixWSzOoaXW5T+qqyH7r/jrR414iYxA/R9zzc/aOuCMSRY/h30gAA="
  },
  "reel-tea": {
    "slug": "reel-tea",
    "alt": "Working at the desk, and tea made in the room",
    "width": 608,
    "height": 1080,
    "aspect": 0.563,
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQBACdASoQABwAPwlwsVArpiSisAgBcCEJaACdMoR3N5LbgAJpcrSEMRoJuAAA3IfFP0fVG2pbtq5rHYf02IE/F9ikIsjs+3Nj7Eh6rehi3J95ftZmV6QA"
  },
  "reel-common": {
    "slug": "reel-common",
    "alt": "Guests around the long table in the common room",
    "width": 608,
    "height": 1080,
    "aspect": 0.563,
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABwAPwl+s1GrqSSisAgBcCEJYwC/OBuEF50MLGEKL3jAAP5aC78bOxgMy/aqtlogT0z+MFq4RqdSzgMBFNQXAp3aTnJk9btiA6Q/sZGqPiQXJWAAAA=="
  }
} as const satisfies Record<string, Rendition>;

export type ImageSlug = keyof typeof IMAGES;
export type VideoSlug = keyof typeof VIDEOS;
